services:
  go:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PATH=/go/bin:${PATH}
    command: air
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /app/docs/swagger.json
    volumes:
      - ./docs:/app/docs
