basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for Go Backend API.
  title: Go Backend API
  version: "1.0"
paths:
  /health:
    get:
      description: サーバーの状態を確認します。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: ヘルスチェック
      tags:
      - Health
swagger: "2.0"
